const config = {
    id: String,
    name: String,
    rank: Number,
    rc: Boolean,
    cc: Boolean,
    ep: Boolean,
    io: Boolean,
    cm: Boolean,
    hc: Boolean,
    dc: Boolean,
    em: Boolean,
    cs: Boolean,
    cf: Boolean,
    bu: Boolean,
    an: Boolean,
    rn: Boolean,
    sn: Boolean,
    mr: Boolean,
}